# Generated by Django 2.2.4 on 2019-09-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190909_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
