# Generated by Django 2.2.4 on 2019-09-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
